### ISSUE TITLE
[Overview] Refactor

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#199]
This issue is an overview of the `refactor` branch and the related features and fixes.

- [x] Service Discovery (#71)
- [x] Lower bufferDelay in Handler (#72) - is now 200ms.
- [x] gRPC over TLS (#85)
- [x] gRPC Error Handling (#89)
- [x] Migrate the network controller to a dedicated component (#90 and #109)
- [x] Gateway Protocol Abstraction (#96)
- [x] Handle uplink for frequencies that are not supported (#98)
- [x] Migrate from Bolt to Redis (#100)
- [x] Airtime calculation (#101)
- [x] Handling extra info in Gateway status messages (#117)
- [x] Support for US and AU Frequency Plans (#119 and #120)
- [x] Downlink port number (#127)
- [x] Don't schedule downlink on gateways that can't do downlink (#140)
- [x] Handle both 16 and 32 bit frame counters correctly (#153)
- [x] Downlink "Encoder" Payload Function (#195)
- [x] Use clean sessions for MQTT client (#203)
- [x] MAC commands (#41)
- [x] ADR
- [x] Advanced MQTT publishes (#159, #193 and #194)
- [x] Support for FSK modulation (#171)

**Comment by htdvisser** [comment]
With `refactor` being renamed to `v2-preview` and all checkboxes being checked, this issue can be closed.
